development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: supportstack
  pool: 5
  username: postgres
  password: root

production:
 adapter: postgresql
 encoding: unicode
 database: supportstack
 pool: 5
 username: postgres
 password: root


test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: supportstack
  pool: 5
  username: postgres
  password: root